acl:
  viewer:
    chatPublic:
      write: false
      read: false
    chatPrivate:
      write: false
      read: false
    presentation:
      write: false
      read: false
    audio:
      write: false
      read: true
    poll:
      write: false
      read: false
    pollVote:
      write: false
      read: false
    whiteboard:
      read: true
  moderator:
    chatPublic:
      write: true
      read: true
    chatPrivate:
      write: true
      read: true
    presentation:
      write: true
      read: false
    lockSetting:
      write: true
      read: false